---
swagger: "2.0"
info:
  version: "1.3.0"
  title: "Data Life-Cycle Framework RAiD API"
  description: "The Data LifeCycle Framework (DLCF – www.dlc.edu.au ) has been initiated by five primary  organisations; Australian Access Federation (AAF), Australia’s Academic and Research Network (AARNet), Australian National Data Service (ANDS), National eResearch Collaboration Tools and Resources (NeCTAR) and Research Data Services (RDS).The DLCF is a nationwide effort to connect research resources and activities such that researchers can make the best use of existing national, state-based, local, and commercial eResearch tools. It aims to provide a simple path to reliable provenance, more effective collaboration across organisations and assist researchers to position themselves to address the growing potential of increasingly open data.The DLCF will connect critical elements and points in time of the data journey from grant approval through to project finalisation, results publication and archiving. It will leverage existing eResearch investment to provide a flexible and dynamic national framework supporting research. The Resource and Activity Persistent identifier(RAiD) is the first of the enabling technologies required for the DLCF. This specification document is for the development of the RAiD service and supporting features."
host: "https://{API_URL_ENDPOINT}"
basePath: "/Testing"
schemes:
- "https"
paths:
  /activity:
    get:
      tags: ["Activity"]
      description: "Returns a list of activities"
      operationId: "getActivities"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "keyword"
        description: "Keyword for activity"
        in: "query"
        required: false
        type: "string"
      - name: "orcid"
        description: "An array of ORCID IDs"
        in: "query"
        required: false
        type: "string"
      - name: "pageSize"
        description: "Number of activites returned"
        in: "query"
        required: false
        type: "string"
      - name: "pageNumber"
        description: "Page order of activities"
        in: "query"
        required: false
        type: "string"
      - name: "researcher"
        description: "Reseacher display name/s associated with the activity"
        in: "query"
        required: false
        type: "string"
      - name: "activityId"
        description: "PURL of the activity"
        in: "query"
        required: false
        type: "string"
      - name: "institution"
        description: "Name or GRID id of the institution"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/ArrayOfActivity"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
    post:
      tags: [
      "Activity"
      ]
      operationId: "postActivity"
      description: "Create and register an ANDS research activity"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        description: "Activity object that needs to be added to the data store"
        name: "ActivityViewModel"
        required: true
        schema:
          $ref: "#/definitions/ActivityViewModel"
      responses:
        200:
          description: "200 OK HTTP Response. RAiD has been created."
          schema:
            $ref: "#/definitions/Activity"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        405:
          description: "405 response. Validation exception"
    options:
      tags: ["Activity"]
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /activity/{identifier}:
    get:
      tags: ["Activity"]
      description: "Return a single activity"
      operationId: "getActivityById"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "identifier"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Activity"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response. Invalid ID supplied."
        404:
          description: "404 response. Activity not found"
    put:
      tags: ["Activity"]
      operationId: "updateActivity"
      description: "Update an existing research activity"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "identifier"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "ActivityViewModel"
        required: true
        schema:
          $ref: "#/definitions/ActivityViewModel"
      responses:
        200:
          description: "200 response. Successful Operation."
          headers:
            Access-Control-Allow-Origin:
              type: "string"
        400:
          description: "400 response. Invalid ID supplied."
        404:
          description: "404 response. Activity not found"
        405:
          description: "405 response. Validation exception"
    options:
      tags: ["Activity"]
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "identifier"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /auth/jwt:
    post:
      tags: ["Auth"]
      operationId: "JWTRedirect"
      description: "POST endpoint to redirect user browser after they have logged into a JWT providing service to the main application."
      responses:
        302:
          description: "302 redirection esponse"
          headers:
            Set-Cookie:
              type: "string"
            location:
              type: "string"
definitions:
  ArrayOfActivity:
    type: "array"
    items:
      $ref: "#/definitions/Activity"
  ActivityViewModel:
    type: "object"
    properties:
      institution:
        type: "string"
        description: "Full descriptive name of the research institution that the activity\
          \ is owned by."
      researchers:
        type: "array"
        description: "An array of researcher ORCIDs that are involved in the research\
          \ activity. It will consist of an ORCID ID at minimum."
        items:
          type: "string"
    description: "Research activity view model for create and update JSON body requests."
  Researcher:
    type: "object"
    required:
    - "orcid"
    properties:
      displayName:
        type: "string"
        description: "Display name from AAF that includes; title, given names and\
          \ last name"
      institution:
        type: "string"
        description: "Name of the affiliation/organisation/institution of the researcher"
      mail:
        type: "string"
        description: "Contact email address of researcher"
      orcid:
        type: "string"
        description: "URI with a 16-digit number that is compatible with the ISO Standard.\
          \ As seen at http://orcid.org"
    description: "AAF affiliated researchers"
  Activity:
    type: "object"
    properties:
      id:
        type: "number"
        description: "Auto-incremented numeric value that along with the year created\
          \ will generate a valid PURL"
      dateCreated:
        type: "string"
        description: "Created date of research activity in 'YYYY-MM-DD HH:MM:SS' format."
      dateModified:
        type: "string"
        description: "Last modified date of research activity in 'YYYY-MM-DD HH:MM:SS'\
          \ format."
      grid:
        type: "string"
        description: "Unique oranisation ID listed by GRID. Example 'grid.1003.2'\
          \ for the University of Queensland: 'https://www.grid.ac/institutes/grid.1003.2'."
      institution:
        type: "string"
        description: "Full descriptive name of the research institution that the activity\
          \ is owned by"
      owner:
        type: "string"
        description: "Mail address of the creator/owner of the activity. Authenticated\
          \ information collected from their AAF authentication JWT token."
      purl:
        type: "string"
        description: "Persistent uniform resource locator that will be registered\
          \ under the ANDS group: ‘http://purl.org/au-research/activity/RAiD/<id string>’\
          . String <id_string> structure is: ‘A<Year>-P00000x’, with ‘00000x’ being\
          \ a numeric with leading zeroes incrementing for each new PURL."
      researchers:
        type: "array"
        description: "An array of researchers that are involved in the research activity.\
          \ It will consist of an ORCID ID at minimum."
        items:
          $ref: "#/definitions/Researcher"
    description: "Research Activity. XML Schema used for reference 'http://services.ands.org.au/documentation/rifcs/1.6.1/schema/activity.xsd'\
      \ and 'http://services.ands.org.au/documentation/rifcs/1.6/vocabs/vocabularies.html'."
