AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RAiDTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "handle"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "handle"
          KeyType: "HASH"
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  AssociationIndexTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        -
          AttributeName: "handle"
          AttributeType: "S"
        -
          AttributeName: "startDate"
          AttributeType: "S"
        -
          AttributeName: "name"
          AttributeType: "S"
        -
          AttributeName: "name-role"
          AttributeType: "S"
        -
          AttributeName: "handle-name"
          AttributeType: "S"
        -
          AttributeName: "handle-type"
          AttributeType: "S"

      KeySchema:
        -
          AttributeName: "handle"
          KeyType: "HASH"
        -
          AttributeName: startDate
          KeyType: RANGE
      GlobalSecondaryIndexes:
        -
          IndexName: "NameIndex"  # Get associated RAiDs of a user
          KeySchema:
            -
              AttributeName: "name"
              KeyType: "HASH"
            -
              AttributeName: "startDate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "endDate"
              - "handle"
              - "raidName"
              - "role"
        -
          IndexName: "NameRoleIndex"  # Special associations of a user to a RAiD, example: finding RAiDs a user owns
          KeySchema:
            -
              AttributeName: "name-role"
              KeyType: "HASH"
            -
              AttributeName: "startDate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "endDate"
              - "handle"
              - "raidName"
        -
          IndexName: "HandleNameIndex"  #  Find an assocation of user and a RAiD. Can be used for permission checking.
          KeySchema:
            -
              AttributeName: "handle-name"
              KeyType: "HASH"
            -
              AttributeName: "startDate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "endDate"
        -
          IndexName: "HandleTypeIndex"  #  Find and split associations of a RAiD by a type of user ('service' or 'instution')
          KeySchema:
            -
              AttributeName: "handle-type"
              KeyType: "HASH"
            -
              AttributeName: "startDate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "name"
              - "endDate"

  ContributorsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "orcid"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "orcid"
          KeyType: "HASH"

  ContributorInvitationsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "email"
          AttributeType: "S"
        - AttributeName: "creationDate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "email"
          KeyType: "HASH"
        - AttributeName: "creationDate"
          KeyType: "RANGE"

  RaidContributorsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "handle"
          AttributeType: "S"
        - AttributeName: "orcid"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "handle"
          KeyType: "HASH"
        - AttributeName: "orcid"
          KeyType: "RANGE"

Outputs:
  RaidDB:
    Value: !Ref 'RAiDTable'

  RAiDAssociationDB:
    Value: !Ref 'AssociationIndexTable'

  RaidDBStreamArn:
    Value:
      Fn::GetAtt:
        - RAiDTable
        - StreamArn

  ContributorsDB:
    Value: !Ref 'ContributorsTable'

  ContributorInvitationsDB:
    Value: !Ref 'ContributorInvitationsTable'

  RaidContributorsDB:
    Value: !Ref 'RaidContributorsTable'

