# To deploy for the first time, and for each update,
# run both of the following commands in order:
#
# aws cloudformation package \
# --template-file template.yaml \
# --output-template-file template-out.yaml \
# --s3-bucket <your-s3-bucket-name>
#
# aws cloudformation deploy \
# --template-file <path-to-file>/template-out.yaml \
# --stack-name <STACK_NAME>
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: RAiD AWS resources

Resources:
  RAiDTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "handle"
          AttributeType: "S"
        -
          AttributeName: "creationDate"
          AttributeType: "S"
        -
          AttributeName: "owner"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "handle"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        -
          IndexName: "OwnerIndex"
          KeySchema:
            -
              AttributeName: "owner"
              KeyType: "HASH"
            -
              AttributeName: "creationDate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "handle"
              - "startDate"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        
  ProviderIndexTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "provider"
          AttributeType: "S"
        -
          AttributeName: "handle"
          AttributeType: "S"
        -
          AttributeName: "startDate"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "provider"
          KeyType: "HASH"
        -
          AttributeName: handle
          KeyType: RANGE
      LocalSecondaryIndexes:
        - 
          IndexName: StartDateIndex
          KeySchema:
            -
              AttributeName: provider
              KeyType: HASH
            -
              AttributeName: startDate
              KeyType: RANGE
          Projection:
              ProjectionType: "INCLUDE"
              NonKeyAttributes:
                - "handle"
                - "endDate"
      GlobalSecondaryIndexes:
        -
          IndexName: "HandleProviderIndex"
          KeySchema:
            -
              AttributeName: "handle"
              KeyType: "HASH"
            -
              AttributeName: "provider"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "startDate"
              - "endDate"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  RaidDB:
    Value: !Ref 'RAiDTable'
  RaidProviderDB:
    Value: !Ref 'ProviderIndexTable'
