# NOTE: Before using this template, replace the <<region>> and <<account>> fields
#       in Lambda integration URI in the swagger file to region and accountId 
#       you are deploying to
#
# To deploy for the first time, and for each update,
# run both of the following commands in order:
#
# aws cloudformation package \
# --template-file template.yaml \
# --output-template-file template-out.yaml \
# --s3-bucket <your-s3-bucket-name>
#
# aws cloudformation deploy \=
# --template-file <path-to-file>/template-out.yaml \
# --stack-name <STACK_NAME>  \
# --parameter-overrides JwtSecret=<<jwt-secret>> \
# --capabilities CAPABILITY_IAM
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: RAiD AWS resources

Parameters:
  Tracing:
    Type: String
    Default: Active
    AllowedValues:
      - Active
      - PassThrough
  JwtIssuerSelf:
    Type: String
    Default: https://www.raid.org.au
  JwtIssuerThirdParty:
    Type: String
    Default: https://rapid.aaf.edu.au
  JwtAudience:
    Type: String
    Default: https://api.raid.org.au
  JwtSecret:
    Type: String
  ProviderRole:
    Type: String
    Default: service

Resources:
  # API
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: swagger.yaml
      StageName: Prod
      Variables:
        CustomAuthorizer: !Ref CustomAuthorizer
        CustomAuthorizerRole: !Ref CustomAuthorizerRole
        CreateRaidFunction: !Ref CreateRaid
        GetOwnerRaidsFunction: !Ref GetOwnerRaids
        GetProviderRaidsFunction: !Ref GetProviderRaids
        GetRaidProvidersFunction: !Ref GetRaidProviders
  # IAM
  ## General
  LogsXrayLambdaPolicy:
    Type: "AWS::IAM::Policy"
    DependsOn: [CustomAuthorizerRole, CrudLambdaIAMRole]
    Properties:
      PolicyName: GeneralLambdaPolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:PutLogEvents",
            "xray:PutTraceSegments",
            "xray:PutTelemetryRecords"
          ]
          Resource: ["*"]
      Roles: [!Ref CustomAuthorizerRole, !Ref CrudLambdaIAMRole]

  CrudLambdaIAMRole:
      Type: "AWS::IAM::Role"
      Properties:
          Path: "/"
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "sts:AssumeRole"
                Principal:
                  Service:
                    - "lambda.amazonaws.com"
                    - "apigateway.amazonaws.com"
  CrudLambdaPolicy:
    Type: "AWS::IAM::Policy"
    DependsOn: [CrudLambdaIAMRole]
    Properties:
      PolicyName: CrudLambdaPolicy
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: [
            "ec2:DescribeNetworkInterfaces", 
            "ec2:CreateNetworkInterface", 
            "ec2:DeleteNetworkInterface",
            "dynamodb:BatchGetItem",
            "dynamodb:BatchWriteItem",
            "dynamodb:DeleteItem",
            "dynamodb:GetItem",
            "dynamodb:PutItem",
            "dynamodb:Query",
            "dynamodb:Scan",
            "dynamodb:UpdateItem"

          ]
          Resource: ["*"]
      Roles: [!Ref CrudLambdaIAMRole]
  
  ## Custom Authorizer
  CustomAuthorizerRole:
      Type: "AWS::IAM::Role"
      Properties:
          Path: "/"
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "sts:AssumeRole"
                Principal:
                  Service:
                    - "lambda.amazonaws.com"
                    - "apigateway.amazonaws.com"
  CustomAuthorizerPolicy:
    Type: "AWS::IAM::Policy"
    DependsOn: [CustomAuthorizerRole]
    Properties: 
      PolicyName: AuthorizerPolicy
      PolicyDocument:
        Statement:
        -
          Effect: Allow
          Action: [
            "lambda:InvokeFunction",
            "lambda:CreateEventSourceMapping",
            "s3:GetObject",
            "s3:GetObjectVersion",
            "s3:GetBucketVersioning"
          ]
          Resource: "*"
      Roles: [!Ref CustomAuthorizerRole]

  # Serverless
  ## Custom Authorizer
  CustomAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: auth.jwt_validation_handler
      Runtime: python2.7
      Role: !GetAtt CustomAuthorizerRole.Arn
      Environment:
        Variables:
          JWT_ISSUER_SELF:
            Ref: JwtIssuerSelf
          JWT_ISSUER_3RD_PARTY:
            Ref: JwtIssuerThirdParty
          JWT_AUDIENCE:
            Ref: JwtAudience
          JWT_SECRET:
            Ref: JwtSecret
          PROVIDER_ROLE:
            Ref: ProviderRole
  ## RAiD CRUD
  CreateRaid:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: raid.create_handler
      Runtime: python2.7
      Role: !GetAtt CrudLambdaIAMRole.Arn
      Environment:
        Variables:
          RAID_TABLE:
            Ref: RAiDTable
          PROVIDER_TABLE:
            Ref: ProviderIndexTable
      Events:
        CreateRaidHandle:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: POST
  GetOwnerRaids:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: raid.get_owner_raids_handler
      Runtime: python2.7
      Role: !GetAtt CrudLambdaIAMRole.Arn
      Environment:
        Variables:
          RAID_TABLE:
            Ref: RAiDTable
          PROVIDER_TABLE:
            Ref: ProviderIndexTable
      Events:
        GetOwnerRaidsHandle:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /owner
            Method: GET
  GetProviderRaids:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: raid.get_provider_raids_handler
      Runtime: python2.7
      Role: !GetAtt CrudLambdaIAMRole.Arn
      Environment:
        Variables:
          RAID_TABLE:
            Ref: RAiDTable
          PROVIDER_TABLE:
            Ref: ProviderIndexTable
      Events:
        GetProviderRaidsHandle:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /provider/{providerId+}
            Method: GET
  GetRaidProviders:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: raid.get_raid_providers_handler
      Runtime: python2.7
      Role: !GetAtt CrudLambdaIAMRole.Arn
      Environment:
        Variables:
          RAID_TABLE:
            Ref: RAiDTable
          PROVIDER_TABLE:
            Ref: ProviderIndexTable
      Events:
        GetRaidProvidersHandle:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /RAiD/{raidId}/providers
            Method: GET
  # Database
  RAiDTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "handle"
          AttributeType: "S"
        -
          AttributeName: "creationDate"
          AttributeType: "S"
        -
          AttributeName: "owner"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "handle"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        -
          IndexName: "OwnerIndex"
          KeySchema:
            -
              AttributeName: "owner"
              KeyType: "HASH"
            -
              AttributeName: "creationDate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "handle"
              - "startDate"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5   
  ProviderIndexTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "provider"
          AttributeType: "S"
        -
          AttributeName: "handle"
          AttributeType: "S"
        -
          AttributeName: "startDate"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "provider"
          KeyType: "HASH"
        -
          AttributeName: handle
          KeyType: RANGE
      LocalSecondaryIndexes:
        - 
          IndexName: StartDateIndex
          KeySchema:
            -
              AttributeName: provider
              KeyType: HASH
            -
              AttributeName: startDate
              KeyType: RANGE
          Projection:
              ProjectionType: "INCLUDE"
              NonKeyAttributes:
                - "handle"
                - "endDate"
      GlobalSecondaryIndexes:
        -
          IndexName: "HandleProviderIndex"
          KeySchema:
            -
              AttributeName: "handle"
              KeyType: "HASH"
            -
              AttributeName: "provider"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes:
              - "startDate"
              - "endDate"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  RaidDB:
    Value: !Ref 'RAiDTable'
  RaidProviderDB:
    Value: !Ref 'ProviderIndexTable'
